Organize README.md
johnalanwoods/maintained-modern-unix pull request #26
Opened 2024-07-30 13:41 UTC by fcolecumberri

2024-08-16 09:16 UTC, port19x approved these changes
I like it. Categorizing the tools makes a lot of sense

2024-09-04 17:15 UTC, johnalanwoods commented
@yozachar - good with you?

2024-09-05 04:47 UTC, yozachar requested changes
Looks good.

2024-09-05 04:47 UTC, yozachar commented on README.md
> +<h2 align="center">Manuals/Docs Utils</h2>
Keep sub headings to the left.

```md
## Manual/Doc Utils
```

2024-09-05 04:55 UTC, yozachar requested changes

2024-09-05 04:55 UTC, yozachar commented on README.md
> +<h2 align="center">System Monitor</h2>
```md
## System Monitor Uitls
```

2024-09-05 04:55 UTC, yozachar commented on README.md
> +<h2 align="center">Unix Utils Clones/Improvements</h2>
```md
### GNU/*Nix Clone Utils
```

2024-09-05 04:55 UTC, yozachar commented on README.md
> +<h2 align="center">Network/Web Related</h2>
```md
## Network Utils
```

2024-09-05 04:55 UTC, yozachar commented on README.md
> +<h2 align="center">Git/Diff</h2>
```md
## Git/Diff Utils
```

2024-09-05 04:55 UTC, yozachar commented on README.md
> +<h2 align="center">Misc</h2>
```md
## Misc. Utils
```

2024-09-05 15:23 UTC, fcolecumberri commented
Changes done.

2024-09-06 10:10 UTC, merged

2024-09-06 10:10 UTC, johnalanwoods commented
Merged and thank you!